### ISSUE TITLE
Demo跑不起来

### ISSUE THREAD

**Issue by 5kccp** [tencentyun/cloudgame-ios-sdk#2]
Demo跑步起来，提示下面错误：
申请云端机器失败:{
    NSErrorFailingURLKey = "xxxxx/StartGame";
    NSErrorFailingURLStringKey = "xxxxx/StartGame";
    NSLocalizedDescription = "unsupported URL";
    NSUnderlyingError = "Error Domain=kCFErrorDomainCFNetwork Code=-1002 \"(null)\"";
    "_NSURLErrorFailingURLSessionTaskErrorKey" = "LocalDataTask <89A71F39-518F-41A1-8287-930430177A73>.<1>";
    "_NSURLErrorRelatedURLSessionTaskErrorKey" =     (
        "LocalDataTask <89A71F39-518F-41A1-8287-930430177A73>.<1>"
    );
}

**Comment by the1dog** [comment]
> 

需要在腾讯云 应用云渲染/云游戏购买并发之后获取API KEY，然后部署自己的业务后台之后通过Demo请求业务后台地址。
Demo中没有示例地址哈
